definitions:
  response.ResponseMessage:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
host: localhost:8100
info:
  contact:
    name: flaravel
  description: 葫芦家商城v2
  license: {}
  title: 葫芦家
  version: "2.0"
paths:
  /api/admin/user:
    post:
      consumes:
      - multipart/form-data
      description: '""'
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 手机号
        in: formData
        name: phone
        required: true
        type: string
      - description: 角色
        in: body
        name: roles
        schema:
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.ResponseMessage'
        "401":
          description: Token解析失败
          schema:
            $ref: '#/definitions/response.ResponseMessage'
        "422":
          description: 请求参数缺失或者不正确返回
          schema:
            $ref: '#/definitions/response.ResponseMessage'
      security:
      - Bearer: []
      summary: 创建管理员
      tags:
      - 后台
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
